loevgaard_dandomain_altapay_api:
    resource: "@LoevgaardDandomainAltapayBundle/Controller/ApiController.php"
    type: rest

loevgaard_dandomain_altapay:
    resource: "@LoevgaardDandomainAltapayBundle/Controller/"
    type: annotation