services:
    loevgaard_dandomain_altapay.form.callback:
        class: Loevgaard\DandomainAltapayBundle\Form\CallbackType
        arguments: ['@loevgaard_dandomain_altapay.callback_manager']
        tags:
            - { name: form.type }

    loevgaard_dandomain_altapay.altapay_client:
        class: Loevgaard\AltaPay\Client
        arguments:
            - "%loevgaard_dandomain_altapay.altapay_username%"
            - "%loevgaard_dandomain_altapay.altapay_password%"

    loevgaard_dandomain_altapay.terminal_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\TerminalManager
        arguments:
            - "@doctrine"
            - "%loevgaard_dandomain_altapay.terminal_class%"
    loevgaard_dandomain_altapay.payment_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\PaymentManager
        arguments:
            - "@doctrine"
            - "%loevgaard_dandomain_altapay.payment_class%"
        calls:
            - [setOrderManager, ["@loevgaard_dandomain_foundation.order_manager"]]
            - [setOrderLineManager, ["@loevgaard_dandomain_foundation.order_line_manager"]]
            - [setSiteManager, ["@loevgaard_dandomain_foundation.site_manager"]]
            - [setCustomerManager, ["@loevgaard_dandomain_foundation.customer_manager"]]
            - [setDeliveryManager, ["@loevgaard_dandomain_foundation.delivery_manager"]]
            - [setPaymentMethodManager, ["@loevgaard_dandomain_foundation.payment_method_manager"]]
            - [setShippingMethodManager, ["@loevgaard_dandomain_foundation.shipping_method_manager"]]
            - [setProductManager, ["@loevgaard_dandomain_foundation.product_manager"]]

    loevgaard_dandomain_altapay.callback_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\CallbackManager
        arguments:
            - "@doctrine"
            - "%loevgaard_dandomain_altapay.callback_class%"