services:
    loevgaard_dandomain_altapay.form.callback:
        class: Loevgaard\DandomainAltapayBundle\Form\CallbackType
        arguments: ['@loevgaard_dandomain_altapay.callback_manager']
        tags:
            - { name: form.type }

    loevgaard_dandomain_altapay.altapay_client:
        class: Loevgaard\AltaPay\Client
        arguments:
            - "%loevgaard_dandomain_altapay.altapay_username%"
            - "%loevgaard_dandomain_altapay.altapay_password%"

    loevgaard_dandomain_altapay.terminal_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\TerminalManager
        arguments:
            - "@doctrine"
            - "%loevgaard_dandomain_altapay.terminal_class%"

    loevgaard_dandomain_altapay.callback_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\CallbackManager
        arguments:
            - "@doctrine"
            - "%loevgaard_dandomain_altapay.callback_class%"