services:
    # Commands
    loevgaard_dandomain_altapay.ping_altapay_command:
        class: Loevgaard\DandomainAltapayBundle\Command\PingAltapayCommand
        arguments:
            - "@loevgaard_dandomain_altapay.altapay_client"
        tags: [console.command]

    loevgaard_dandomain_altapay.sync_terminals_command:
        class: Loevgaard\DandomainAltapayBundle\Command\SyncTerminalsCommand
        arguments:
            - "@loevgaard_dandomain_altapay.terminal_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_altapay.consume_webhook_queue_command:
        class: Loevgaard\DandomainAltapayBundle\Command\ConsumeWebhookQueueCommand
        arguments:
            - "@loevgaard_dandomain_altapay.webhook_exchange_repository"
            - "@jms_serializer.serializer"
        tags: [console.command]

    loevgaard_dandomain_altapay.enqueue_webhooks_command:
        class: Loevgaard\DandomainAltapayBundle\Command\EnqueueWebhooksCommand
        arguments:
            - "@loevgaard_dandomain_altapay.webhook_exchange_repository"
            - "@loevgaard_dandomain_altapay.event_repository"
            - "@jms_serializer.serializer"
        tags: [console.command]

    # Twig extensions
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    # Listeners
    loevgaard_dandomain_altapay.exception_listener:
        class: Loevgaard\DandomainAltapayBundle\EventListener\ExceptionListener
        arguments:
            - "@templating.engine.twig"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    loevgaard_dandomain_altapay.controller_listener:
        class: Loevgaard\DandomainAltapayBundle\EventListener\ControllerListener
        arguments:
            - "@loevgaard_dandomain_altapay.transaction_logger"
            - "@annotation_reader"
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    loevgaard_dandomain_altapay.response_listener:
        class: Loevgaard\DandomainAltapayBundle\EventListener\ResponseListener
        arguments:
            - "@loevgaard_dandomain_altapay.transaction_logger"
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    # Repositories
    loevgaard_dandomain_altapay.site_setting_repository:
        class: Loevgaard\DandomainAltapayBundle\Entity\SiteSettingRepository
        arguments:
            - "@doctrine"
            - "@knp_paginator"
            - Loevgaard\DandomainAltapayBundle\Entity\SiteSetting

    loevgaard_dandomain_altapay.http_transaction_repository:
        class: Loevgaard\DandomainAltapayBundle\Entity\HttpTransactionRepository
        arguments:
            - "@doctrine"
            - "@knp_paginator"
            - Loevgaard\DandomainAltapayBundle\Entity\HttpTransaction

    loevgaard_dandomain_altapay.terminal_repository:
        class: Loevgaard\DandomainAltapayBundle\Entity\TerminalRepository
        arguments:
            - "@doctrine"
            - "@knp_paginator"
            - Loevgaard\DandomainAltapayBundle\Entity\Terminal
        calls:
            - [setContainer, ["@service_container"]]

    loevgaard_dandomain_altapay.payment_repository:
        class: Loevgaard\DandomainAltapayBundle\Entity\PaymentRepository
        arguments:
            - "@doctrine"
            - "@knp_paginator"
            - Loevgaard\DandomainAltapayBundle\Entity\Payment

    loevgaard_dandomain_altapay.event_repository:
        class: Loevgaard\DandomainAltapayBundle\Entity\EventRepository
        arguments:
            - "@doctrine"
            - "@knp_paginator"
            - Loevgaard\DandomainAltapayBundle\Entity\Event
            - "@jms_serializer.serializer"

    loevgaard_dandomain_altapay.webhook_exchange_repository:
        class: Loevgaard\DandomainAltapayBundle\Entity\WebhookExchangeRepository
        arguments:
            - "@doctrine"
            - "@knp_paginator"
            - Loevgaard\DandomainAltapayBundle\Entity\WebhookExchange

    # Misc
    loevgaard_dandomain_altapay.transaction_logger:
        class: Loevgaard\DandomainAltapayBundle\Http\TransactionLogger
        arguments:
            - "@loevgaard_dandomain_altapay.http_transaction_repository"

    loevgaard_dandomain_altapay.altapay_client:
        class: Loevgaard\AltaPay\Client
        arguments:
            - "%loevgaard_dandomain_altapay.altapay_username%"
            - "%loevgaard_dandomain_altapay.altapay_password%"
            - "%loevgaard_dandomain_altapay.altapay_url%"

    loevgaard_dandomain_altapay.altapay_callback_handler:
        class: Loevgaard\AltaPay\CallbackHandler

    loevgaard_dandomain_altapay.terminal_synchronizer:
        class: Loevgaard\DandomainAltapayBundle\Synchronizer\TerminalSynchronizer
        arguments:
            - "@loevgaard_dandomain_altapay.terminal_repository"
            - "@loevgaard_dandomain_altapay.altapay_client"

    loevgaard_dandomain_altapay.payment_handler:
        class: Loevgaard\DandomainAltapayBundle\Handler\PaymentHandler
        arguments:
            - "@loevgaard_dandomain_altapay.altapay_client"
            - "@loevgaard_dandomain_altapay.payment_repository"

    loevgaard_dandomain_altapay.site_settings_provider:
        class: Loevgaard\DandomainAltapayBundle\Provider\SiteSettingsProvider
        arguments:
            - "@service_container"
            - "@loevgaard_dandomain_altapay.site_setting_repository"