services:
    loevgaard_dandomain_altapay.altapay_client:
        class: Loevgaard\AltaPay\Client
        arguments:
            - "%loevgaard_dandomain_altapay.altapay_username%"
            - "%loevgaard_dandomain_altapay.altapay_password%"

    loevgaard_dandomain_altapay.terminal_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\TerminalManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%loevgaard_dandomain_altapay.terminal_class%"
    loevgaard_dandomain_altapay.payment_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\PaymentManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@loevgaard_dandomain_altapay.order_line_manager"
            - "%loevgaard_dandomain_altapay.payment_class%"

    loevgaard_dandomain_altapay.order_line_manager:
        class: Loevgaard\DandomainAltapayBundle\Manager\OrderLineManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%loevgaard_dandomain_altapay.order_line_class%"